version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "mashadb"
      POSTGRES_USER: "mashapg"
      POSTGRES_PASSWORD: "mashapg"
    volumes:
      - ./sql_scripts/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
